services:
  app:
    volumes:
      - ticketra-storage:/var/www/html/storage
      - ticketra-db:/var/www/html/database
      - ./app:/var/www/html/app
      - ./bootstrap:/var/www/html/bootstrap
      - ./config:/var/www/html/config
      - ./database/migrations:/var/www/html/database/migrations
      - ./database/seeders:/var/www/html/database/seeders
      - ./database/factories:/var/www/html/database/factories
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      RUN_MIGRATIONS: "true"
